### ISSUE TITLE
Help the user also have system-wide access to Floodplain/Terrace tools

### ISSUE THREAD

**Issue by awickert** [umn-earth-surface/LSDTTInstallationGuides#3]
At the place where it is written:
"Going forward, you can run the terrace driver by navigating to this folder and typing the command:"

Guide the user to (in a similar way to the above directions) add *LSDTT Foodplains Terraces* `bin` to the `.profile` and system-wide path.

**Comment by awickert** [comment]
The key is in the `./`. Why is it needed for `get_terraces.out` and how does adding a directory containing the executable to your path change this? (No need to answer here -- think & do!)

**Comment by spenprase** [comment]
So, then: 
` export PATH="$PATH:/home/<YOUR_USERNAME>/LSDTopoTools/LSDTopoTools_FloodplainTerraceExtraction/driver_functions_Floodplains-Terraces"`

should do the trick? And going forward you would just type: 

`get_terraces.out /path/to/DEM/location/ name_of_parameter_file.param`

I'm asking here instead of testing it and having a definitive answer because Robert is using his computer at the moment!

**Comment by awickert** [comment]
Precisely!
